type PDFPageProps = {
  subTitle: string;
  rightTopLine: string;
  rightSubLine: string;
  teacherLine?: string;
  pageNumber: number;
  totalPages: number;
  footerLeft?: React.ReactNode;
  children: React.ReactNode;
};

export function PDFPage({
  subTitle,
  rightTopLine,
  rightSubLine,
  teacherLine,
  pageNumber,
  totalPages,
  footerLeft,
  children,
}: PDFPageProps) {
  return (
    <div
      className="pdf-page px-4 py-6 md:px-14 md:py-12"
      style={{
        maxWidth: "780px",
        margin: "0 auto 0.5rem",
        background: "#fff",
        borderRadius: "4px",
        boxShadow: "0 2px 16px rgba(0,0,0,0.08), 0 0 0 0.5px rgba(0,0,0,0.04)",
      }}
    >
      <div
        className="flex items-start justify-between"
        style={{
          paddingBottom: "1.25rem",
          borderBottom: "1.5px solid var(--accent-gold)",
          marginBottom: "1.5rem",
        }}
      >
        <div>
          <div
            className="flex items-center"
            style={{
              gap: "8px",
              lineHeight: 1.1,
            }}
          >
            <img
              src="/gemmpen-logo.webp"
              alt="GemmPen"
              style={{ height: "24px", width: "auto" }}
            />
            <span
              style={{
                fontFamily: "var(--font-cormorant), Georgia, serif",
                fontSize: "1.625rem",
                fontWeight: 600,
                color: "var(--text-primary)",
              }}
            >
              GemmPen
            </span>
          </div>
          <div
            style={{
              fontSize: "0.625rem",
              color: "var(--text-muted)",
              letterSpacing: "1px",
              textTransform: "uppercase",
              marginTop: "0.125rem",
            }}
          >
            {subTitle}
          </div>
        </div>
        <div className="text-right">
          <div style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>
            {rightTopLine}
          </div>
          <div
            style={{
              fontSize: "0.75rem",
              color: "var(--text-secondary)",
              marginTop: "0.125rem",
            }}
          >
            {rightSubLine}
          </div>
          {teacherLine && (
            <div
              style={{
                fontSize: "0.6875rem",
                fontWeight: 500,
                color: "var(--accent-gold)",
                marginTop: "0.25rem",
              }}
            >
              {teacherLine}
            </div>
          )}
        </div>
      </div>

      {children}

      <div
        className="flex items-center justify-between"
        style={{
          marginTop: "2rem",
          paddingTop: "0.875rem",
          borderTop: "0.5px solid #E4DDD2",
        }}
      >
        <div
          style={{
            fontSize: "0.625rem",
            color: "var(--text-muted)",
            lineHeight: 1.5,
          }}
        >
          {footerLeft ?? (
            <>
              Generated by GemmPen - powered by Gemma 4
              <br />
              This feedback was drafted with the help of AI. All grades were assigned and verified by your teacher personally.
            </>
          )}
        </div>
        <div
          style={{
            fontFamily: "var(--font-cormorant), Georgia, serif",
            fontSize: "0.875rem",
            fontWeight: 600,
            color: "var(--text-muted)",
          }}
        >
          {pageNumber} / {totalPages}
        </div>
      </div>
    </div>
  );
}
